services:
  add:
    entrypoint: /code/entrypoint
    environment:
      CARGO_HOME: /cargo-home
      CARGO_TARGET_DIR: /cargo-target
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      OTEL_EXPORTER_SERVICE_NAME: add
    image: rust:1.53
    ports:
      - 8081:80
    volumes:
      - ./:/code
      - add_target:/cargo-target
      - add_home:/cargo-home
    working_dir: /code/add
  calculator:
    entrypoint: /code/entrypoint
    environment:
      CARGO_HOME: /cargo-home
      CARGO_TARGET_DIR: /cargo-target
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      OTEL_EXPORTER_SERVICE_NAME: calculator
    image: rust:1.53
    ports:
      - 8080:80
    volumes:
      - ./:/code
      - calculator_target:/cargo-target
      - calculator_home:/cargo-home
    working_dir: /code/calculator
  div:
    entrypoint: /code/entrypoint
    environment:
      CARGO_HOME: /cargo-home
      CARGO_TARGET_DIR: /cargo-target
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      OTEL_EXPORTER_SERVICE_NAME: div
    image: rust:1.53
    ports:
      - 8084:80
    volumes:
      - ./:/code
      - div_target:/cargo-target
      - div_home:/cargo-home
    working_dir: /code/div
  jaeger:
    image: jaegertracing/all-in-one:1.23
    ports:
      - 5778:5778
      - 16686:16686
  mul:
    entrypoint: /code/entrypoint
    environment:
      CARGO_HOME: /cargo-home
      CARGO_TARGET_DIR: /cargo-target
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      OTEL_EXPORTER_SERVICE_NAME: mul
    image: rust:1.53
    ports:
      - 8083:80
    volumes:
      - ./:/code
      - mul_target:/cargo-target
      - mul_home:/cargo-home
    working_dir: /code/mul
  sub:
    entrypoint: /code/entrypoint
    environment:
      CARGO_HOME: /cargo-home
      CARGO_TARGET_DIR: /cargo-target
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
      OTEL_EXPORTER_SERVICE_NAME: sub
    image: rust:1.53
    ports:
      - 8082:80
    volumes:
      - ./:/code
      - sub_target:/cargo-target
      - sub_home:/cargo-home
    working_dir: /code/sub
version: "3.1"
volumes:
  add_home: {}
  add_target: {}
  calculator_home: {}
  calculator_target: {}
  div_home: {}
  div_target: {}
  mul_home: {}
  mul_target: {}
  sub_home: {}
  sub_target: {}
