[package]
name = "add"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
actix-web-opentelemetry = { git = "https://github.com/lily-mara/actix-web-opentelemetry", branch = "opentelemetry-0.14" }
tracing-batteries = { path = "../tracing-batteries" }
